In [31]:
import numpy as np

# Example dimensions
num_videos = 2
num_frames_per_video = 3
num_body_parts = 2  # Assuming there are 2 body parts
num_coordinates = 2  # X and Y coordinates

# Initialize an empty 4D array
landmarks_array = np.zeros((num_videos, num_frames_per_video, num_body_parts, num_coordinates))

# Fill the array with random landmark coordinates
for video in range(num_videos):
    for frame in range(num_frames_per_video):
        for body_part in range(num_body_parts):
            # Generate random landmark coordinates for demonstration
            landmarks = np.random.rand(num_coordinates)
            landmarks_array[video, frame, body_part, :] = landmarks

print(landmarks_array.shape)
print(landmarks_array)
print(landmarks_array[0][1][1][0])

(2, 3, 2, 2)
[[[[0.02152952 0.84722016]
   [0.72626037 0.16949886]]

  [[0.91723579 0.70457952]
   [0.85333435 0.32380562]]

  [[0.87306057 0.38414998]
   [0.5763713  0.78053359]]]


 [[[0.33307525 0.99618028]
   [0.03616348 0.57886288]]

  [[0.28117026 0.4539818 ]
   [0.07724965 0.50027364]]

  [[0.56320437 0.06115465]
   [0.63197558 0.6327468 ]]]]
0.8533343533510791


In [10]:
import numpy as np

# Define input dimensions
num_videos = 5  # Number of videos for the same action
num_frames_per_video = 3  # Number of frames per video
num_body_parts = 2  # Assuming there are 5 body parts
num_coordinates = 2  # X and Y coordinates
num_classes = 2  # Assuming there are 4 action classes

# Generate example data (replace with your actual data)
X_train = np.random.rand(num_videos, num_frames_per_video, num_body_parts, num_coordinates)
y_train = np.random.randint(0, num_classes, size=(num_videos,))

print("X_train shape:", X_train.shape)  # (num_videos, num_frames_per_video, num_body_parts, num_coordinates)
print("y_train shape:", y_train.shape)  # (num_videos,)

print(X_train)
print(y_train)

X_train shape: (5, 3, 2, 2)
y_train shape: (5,)
[[[[0.53045525 0.37590549]
   [0.27882144 0.14017687]]

  [[0.26054077 0.85413362]
   [0.13420446 0.74306258]]

  [[0.49307652 0.0420568 ]
   [0.72568343 0.58097617]]]


 [[[0.71730552 0.46572424]
   [0.6456634  0.28387456]]

  [[0.71395527 0.91484056]
   [0.17754225 0.06993347]]

  [[0.3466766  0.77398984]
   [0.45186156 0.76447896]]]


 [[[0.07299232 0.26525719]
   [0.23608832 0.78667421]]

  [[0.78638702 0.458612  ]
   [0.57113127 0.36204022]]

  [[0.18584336 0.56742608]
   [0.31359595 0.94528516]]]


 [[[0.20448402 0.98674582]
   [0.21313213 0.87669688]]

  [[0.93359215 0.7495475 ]
   [0.88223263 0.2411046 ]]

  [[0.5358757  0.99910318]
   [0.22220082 0.82799158]]]


 [[[0.61517742 0.03848384]
   [0.64674867 0.95852676]]

  [[0.71845278 0.44830303]
   [0.99678073 0.95393931]]

  [[0.38176184 0.89856114]
   [0.20413263 0.12167254]]]]
[0 1 1 0 1]


In [38]:
import numpy as np
import math

In [39]:

num_videos = 5  # Number of videos for the same action
num_frames_per_video = 3  # Number of frames per video
num_body_parts = 2  # Assuming there are 5 body parts
num_coordinates = 2  # X and Y coordinates
num_classes = 2  # Assuming there are 4 action classes

train_videos = np.zeros((num_videos, num_frames_per_video, num_body_parts, num_coordinates))
output = np.zeros(num_videos, dtype=int)

for video in range(num_videos):
    for frame in range(num_frames_per_video):
        for body_part in range(num_body_parts):
            for coordinate in range(num_coordinates):
                landmark = coordinate
                train_videos[video,frame, body_part,coordinate] = landmark

for video in range(num_videos):
    output[video] = np.random.randint(num_classes)
    
print(train_videos)
print(output)


[[[[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]]


 [[[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]]


 [[[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]]


 [[[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]]


 [[[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]

  [[0. 1.]
   [0. 1.]]]]
[0 1 0 1 0]


# Data Collection where each frame is labelled

In [ ]:

no_of_frames = 10
no_of_body_parts = 33
no_of_coordinated = 3

train_x = np.zeros((no_of_frames, no_of_body_parts, no_of_coordinated))

for frame in range(no_of_frames):
    

In [3]:
import cv2

video_path = 'fall.mp4'

video = cv2.VideoCapture('fall.mp4')
total_frames = 0
if not video.isOpened():
    print("failed to open video")

while True:
    success, frame = video.read()
    
    if not success:
        print("Video ended")
        break
        
    cv2.imshow("Frame", frame)
    total_frames += 1
    
    if cv2.waitKey(50) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()
print(f'Total Frames : {total_frames}')

Video ended
Total Frames : 47


In [4]:
video.set(cv2.CAP_PROP_POS_FRAMES, 3)
ret , frame = video.read()
cv2.imshow('frame', frame)
video.release()

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [1]:
import numpy as np

In [8]:
array_with_less_frames = np.array([[1,2,3], [4,5,6], [7,8,9]])
desired_lenght = 20
print(array_with_less_frames.shape)
no_of_padding = desired_lenght - len(array_with_less_frames)

array_with_all_frames = np.pad(array_with_less_frames, ((0, no_of_padding), (0,0)), mode='constant', constant_values=0)

print(array_with_all_frames.shape)
array_with_all_frames

(3, 3)
(20, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# To obtain number of frames in a video

In [2]:
import cv2
import numpy as np

In [11]:
video_path = 'fall.mp4'

video = cv2.VideoCapture(video_path)

if not video.isOpened():
    print("error opening video")

no_of_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))

video.release()

no_of_frames

47

# To obtain list of 30 equally seperated indexes

In [4]:
needed_frames = 30

no_of_frame_indexes = np.linspace(0, no_of_frames - 1, needed_frames, dtype=int)
print(no_of_frame_indexes)
print(len(no_of_frame_indexes))

[ 0  1  3  4  6  7  9 11 12 14 15 17 19 20 22 23 25 26 28 30 31 33 34 36
 38 39 41 42 44 46]
30


# To access frames from indexes

In [31]:
video_path = 'fall.mp4'

video = cv2.VideoCapture(video_path)

if not video.isOpened():
    print("error opening video")

needed_frames = 30
    
no_of_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))

no_of_frame_indexes = np.linspace(0, no_of_frames - 1, needed_frames, dtype=int)
print(no_of_frames)
print(no_of_frame_indexes)
print(len(no_of_frame_indexes))


for frame_index in no_of_frame_indexes:
    video.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
    
    success, frame = video.read()
    
    if not success:
        break
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) == ord('q'):
        break
    
video.release()
cv2.destroyAllWindows()

47
[ 0  1  3  4  6  7  9 11 12 14 15 17 19 20 22 23 25 26 28 30 31 33 34 36
 38 39 41 42 44 46]
30


# Detecting landmarks on a video (Trial)

In [10]:
import cv2
import mediapipe as mp
import numpy as np

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)

video_file = 'testing_video.mp4'

cap = cv2.VideoCapture(video_file)

if not cap.isOpened():
    print("Error opening the video")

#resizing the frame
_, frame = cap.read()
h, w = frame.shape[0], frame.shape[1]
print(h, w)
cv2.namedWindow('Window Name', cv2.WINDOW_NORMAL)  # WINDOW_NORMAL allows resizing
# Resize the window
cv2.resizeWindow('Window Name', w//2, h//2)  # Set the desired width and height

while True:
    success, frame = cap.read()
    
    if not success:
        print("Video ended")
        break
        
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = pose.process(frame_rgb)
    
    mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
    
    cv2.imshow("Window Name", frame)
#     print(frame.shape)
    if cv2.waitKey(1) == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

if results.pose_landmarks:
    print(results.pose_landmarks.landmark[mp_pose.PoseLandmark(0).value])

1280 720
x: 0.7408503293991089
y: 0.3202008605003357
z: -0.48209160566329956
visibility: 0.9999697804450989



## 1. Create a function that iterates through a folder that has all video data
## 2. For each video get landmarks for each frame and append it to an array say training_data
## 3. pre-process each frame array (padding)

In [1]:
import os
import cv2
import mediapipe as mp
import numpy as np

# creating mediapipe objects
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(min_detection_confidence=0.4, min_tracking_confidence=0.4, model_complexity=2)
mp_drawing = mp.solutions.drawing_utils

#defining no of frames we need to depict one action
frames_needed = 30
directory = 'data/'
#define training data array, here we will store all data array for one action
training_data = []
# training_data = np.array(training_data)
counter = 0

#######################################################################################################################

# function to get each frame
def getLandmarksArrayForFrame(results):
    landmarks = []
    
    for i in range(33):
        landmarks.append([results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].x,
                         results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].y,
                         results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].visibility])
    
    landmarks = np.array(landmarks)
    return landmarks

#######################################################################################################################

def getTrainingData(directory):
    # Reading each video and collecting data from it present in data folder
    for video in os.listdir(directory):
        print(video)
        # in this array we will add input of shape (30, 33, 3) of each video and then append it to training_data array
        frame_array = []

        cap = cv2.VideoCapture(video)
        if not cap.isOpened():
            print('Failed to open video')

        #resizing the window
        _, frame = cap.read()
        h, w = frame.shape[0], frame.shape[1]
        print(h, w)
        cv2.namedWindow('frame', cv2.WINDOW_NORMAL)  # WINDOW_NORMAL allows resizing
        # Resize the window
        cv2.resizeWindow('frame', w//2, h//2)  # Set the desired width and height

        # computing required values
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        step = total_frames // frames_needed
        frames_indexes = np.linspace(0, total_frames - 1, frames_needed, dtype=int)

        #printing the values computed for verification
        print(f'Total frames is {total_frames}')
        print(f'step is {step}')
        print(frames_indexes)
        print(f'Lenght of frames index array is {len(frames_indexes)}')
        
        getAllFrames(frames_indexes, cap, frame_array)
        
    cap.release()
        
##############################################################################################################
        
def getAllFrames(frames_indexes, cap, frame_array):
    global counter
    for frame_index in frames_indexes:
        
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
        
        success, frame = cap.read()
        if not success:
            print('Video ended')
        
        # converted to rgb because mediapipe reads images in rgb format
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            
        #detecting landmarks on each frame
        results = pose.process(rgb_frame)
        
        #drawing landmarks
        mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
        
        if results.pose_landmarks:
            frame_array.append(getLandmarksArrayForFrame(results))
        else:
            print(f"landmarks from one frame not detected, frame no is {frame_index}")
            frame_array.append(np.zeros((33,3), dtype=int))
            
#         cv2.imshow("frame", frame)
        counter += 1
        if cv2.waitKey(1) == ord('q'):
            break
            
    frame_array = np.array(frame_array)
    training_data.append(frame_array)
    

##########################################################################################################################
print("calling getTrainingData")
getTrainingData(directory)

training_data = np.array(training_data)
print(training_data.shape)
print(training_data)
print(f'Readed {counter} frames')
cv2.destroyAllWindows()

calling getTrainingData
t_1.mp4
Failed to open video


AttributeError: 'NoneType' object has no attribute 'shape'

In [2]:
import os

def rename_videos(directory, prefix="t_", start_index=1):
    
    # Ensure that the directory exists
    if not os.path.isdir(directory):
        print(f"Error: Directory '{directory}' not found.")
        return
    
    for index, filename in enumerate(os.listdir(directory), start=start_index):
        # Check if the file is a video (you can modify this condition if needed)
        if filename.endswith(".mp4"):
            # Construct the new filename with the prefix and index
            new_filename = f"{prefix}{index}.mp4"
            # Rename the file
            os.rename(os.path.join(directory, filename), os.path.join(directory, new_filename))
            print(f"Renamed '{filename}' to '{new_filename}'")

# Example usage:
directory_path = "data"
rename_videos(directory_path)


Renamed 'video_1.mp4' to 't_1.mp4'


In [1]:
import cv2

vid = cv2.VideoCapture("data/video_30.mp4")

if not vid.isOpened():
    print("eror")
else:
    print("Video is opened")

_, frame = vid.read()
cv2.imshow('frame', frame)
cv2.waitKey(5000)
vid.release()
cv2.destroyAllWindows()

eror


error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [ ]:
import cv2
import os

for file_name in os.listdir('data/'):
    print(file_name)
    vid = cv2.VideoCapture(file_name)

    if not vid.isOpened():
        print("eror")
    else:
        print("Video is opened")
    vid.release()

In [1]:
!pip install --upgrade scipy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 46.2/46.2 MB 1.5 MB/s eta 0:00:00


In [1]:
training_data.shape

NameError: name 'training_data' is not defined

In [12]:
a = np.zeros((33,3), dtype=int)
# a

In [3]:
np.zeros((3), dtype=int)

array([0, 0, 0])

In [11]:
# training_data[0][29]

In [5]:
training_data[0][0]

array([[0.81765854, 0.27486673, 0.99384487],
       [0.81248319, 0.2572858 , 0.99336207],
       [0.81056255, 0.25685763, 0.99422508],
       [0.80827594, 0.2565842 , 0.99603856],
       [0.82536274, 0.25542882, 0.98978627],
       [0.83258897, 0.25356373, 0.98984528],
       [0.83982241, 0.25155866, 0.99049711],
       [0.82265991, 0.25592601, 0.99899238],
       [0.86792797, 0.250718  , 0.9889937 ],
       [0.82393038, 0.28683591, 0.996512  ],
       [0.83471054, 0.28555879, 0.99175006],
       [0.81385827, 0.33010596, 0.99995613],
       [0.99654287, 0.32080239, 0.9941082 ],
       [0.80519223, 0.47398639, 0.98916513],
       [0.94861096, 0.45453531, 0.00676032],
       [0.73577124, 0.60478884, 0.9554764 ],
       [0.94501179, 0.55172557, 0.00643459],
       [0.73883855, 0.64674646, 0.92017543],
       [0.94112611, 0.56863534, 0.01053997],
       [0.73530978, 0.65012616, 0.91404182],
       [0.91760892, 0.56929266, 0.01005783],
       [0.73743844, 0.63432831, 0.85003984],
       [0.

In [1]:
import os
import cv2
import mediapipe as mp
import numpy as np

# creating mediapipe objects
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(min_detection_confidence=0.4, min_tracking_confidence=0.4, model_complexity=2)
mp_drawing = mp.solutions.drawing_utils

#defining no of frames we need to depict one action
frames_needed = 30
directory = 'data'
#define training data array, here we will store all data array for one action
training_data = []
# training_data = np.array(training_data)
counter = 0


# function to get each frame
def getLandmarksArrayForFrame(results):
    landmarks = []
    
    for i in range(33):
        landmarks.append([results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].x,
                         results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].y,
                         results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].visibility])
    
    landmarks = np.array(landmarks)
    return landmarks


# Reading each video and collecting data from it present in data folder
for video in os.listdir(directory):
    print(video)
    # in this array we will add input of shape (30, 33, 3) of each video and then append it to training_data array
    frame_array = []
    
    cap = cv2.VideoCapture(video)
    if not cap.isOpened():
        print('Failed to open video')
    
    #resizing the window
    _, frame = cap.read()
    h, w = frame.shape[0], frame.shape[1]
    print(h, w)
    cv2.namedWindow('frame', cv2.WINDOW_NORMAL)  # WINDOW_NORMAL allows resizing
    # Resize the window
    cv2.resizeWindow('frame', w//2, h//2)  # Set the desired width and height

    # computing required values
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    step = total_frames // frames_needed
    frames_indexes = np.linspace(0, total_frames - 1, frames_needed, dtype=int)
    
    #printing the values computed for verification
    print(f'Total frames is {total_frames}')
    print(f'step is {step}')
    print(frames_indexes)
    print(f'Lenght of frames index array is {len(frames_indexes)}')
    
    # this part is responsible for obtaining landmarks from each frame for a particular frame index
    for frame_index in frames_indexes:
        
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
        
        success, frame = cap.read()
        if not success:
            print('Video ended')
        
        # converted to rgb because mediapipe reads images in rgb format
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            
        #detecting landmarks on each frame
        results = pose.process(rgb_frame)
        
        #drawing landmarks
        mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
        
        if results.pose_landmarks:
            frame_array.append(getLandmarksArrayForFrame(results))
        else:
            print(f"landmarks from one frame not detected, frame no is {frame_index}")
            frame_array.append(np.zeros((33,3), dtype=int))
            
        cv2.imshow("frame", frame)
        counter += 1
        if cv2.waitKey(1) == ord('q'):
            break
            
    frame_array = np.array(frame_array)
    training_data.append(frame_array)
    
training_data = np.array(training_data)
print(training_data.shape)
print(training_data)
print(f'Readed {counter} frames')
cap.release()
cv2.destroyAllWindows()

t_1.mp4
Failed to open video


AttributeError: 'NoneType' object has no attribute 'shape'